### ISSUE TITLE
Please add open source `LICENSE`

### ISSUE THREAD

**Issue by penyuan** [przemub/ics_caldav_sync#1]
What a great script! Thanks for publishing it here. :heart:

However, right now there is no `LICENSE` file in this repository that is an open source license so it is difficult for me to learn from and utilize your amazing work. Could you follow these [easy instructions](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository) in GitHub's documentation to choose and apply a proper open source license for this package, such as the GNU GPLv3. Otherwise, other people won't be allowed to study, share, and build on the code.

If it helps, I'm happy to submit a pull request with the needed changes. Thanks!

**Comment by przemub** [comment]
I am very glad that you liked it :) Done.

**Comment by penyuan** [comment]
OMG that was amazingly fast. Thank you so much and best wishes!
