### ISSUE TITLE
Issues with arrow package while installation

### ISSUE THREAD

**Issue by therealmaxmoon** [przemub/ics_caldav_sync#2]
I've installed newest Python and created a new virtualenv and tried to install all packages with

```pip3.11 install -r requirements.txt```

But it throws the arrow:

```
ERROR: Cannot install -r requirements.txt (line 5) and arrow==1.2.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested arrow==1.2.1
    ics 0.7 depends on arrow<0.15 and >=0.11
```

**Comment by przemub** [comment]
Hi @therealmaxmoon, thanks for the report! I've updated the requirements file and it seems to install correctly. Let me know if anything's still wrong.
