### ISSUE TITLE
Wrong timezone / appointments delayed

### ISSUE THREAD

**Issue by neverchained** [przemub/ics_caldav_sync#5]
When syncing from an Exchange Online ics-url to my CalDAV-server, all appointments are two hours delayed. Is there any way to set the correct timezone for the sync?

**Comment by przemub** [comment]
Hi guys,

I probably should curse you before all gods for sending me down the timezone hole - I guess that's what I get for making something related to calendars. (Joking, I'm happy someone finds this useful!)

I made (hopefully) an universal solution which should require just setting `TIMEZONE` to your desired timezone. Please test it out - it's on `timezone_support` branch (PR: https://github.com/przemub/ics_caldav_sync/pull/6).

Once it's confirmed working, I'll merge it.

Best wishes,
Prem

**Comment by przemub** [comment]
Hi both, I've merged the PR. Please let me know if you keep having problems.
