### ISSUE TITLE
Support Updating without removing all events from a Calendar

### ISSUE THREAD

**Issue by nordy1145** [przemub/ics_caldav_sync#7]
Wondering if it's possible to add the ability to not completely wipe a calendar of other events if syncing a remote calendar to a local one. For example, Calendar "Home" has events added manually and events added via a remote calendar, currently importing an .ics file. It'd be great if we could keep all events on the calendar and only update the new/existing events from the remote calendar. 
I'll be working through this the next few weeks myself, but wanted to throw it out there!

**Comment by przemub** [comment]
I added such an option under KEEP_LOCAL environment variable. Please let me know if it works for you :)

**Comment by nordy1145** [comment]
Was able to successfully keep existing events added outside of the remote ics file!!
