### ISSUE TITLE
Baikal backend with Time Zones

### ISSUE THREAD

**Issue by nordy1145** [przemub/ics_caldav_sync#8]
Just wanted to share in case any others have the same issue I was having with Time zones and Baikal.  When I would set the time zone in environment variable, it would display in my calendar incorrectly. I had to remove the Time Zone variable from the config for everything to display correctly.  If the Time Zone variable was empty "" instead of non existent it wouldn't create the DSTART time correctly, it was missing the trailing Z at the end of the timestamp. 
So either set a time zone or remove the variable and you should be good to go!

**Comment by przemub** [comment]
Thanks for the report. This should be fixed with a59454b.
